# netlify.toml
[build]
  publish = "build"

[[redirects]]
  # Proxy all API calls to the backend
  from = "/api/*"
  to = "https://pro-api.coinmarketcap.com/v1/:splat" # todo: take it from env
  status = 200
  force = true