# netlify.toml

[[redirects]]
  # Proxy all API calls to the backend
  from = "/api/*"
  to = "https://pro-api.coinmarketcap.com/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
